version: '3.7'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'bookland'
      MYSQL_PASSWORD: '12345'

  mysql_test:
    image: 'mysql:8.0'
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'bookland_test'
      MYSQL_PASSWORD: '12345'